[project]
name = "dash-clientside-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=2.18.2",
    "dash-ag-grid>=31.3.0",
    "dash-mantine-components>=0.15.3",
    "numpy>=2.2.3",
    "polars>=1.23.0",
]
